config/routes.rb
Rails.application.routes.draw do

  resources :genres, except: :new
  resources :languages, except: :new

  resources :movies
  root 'movies#index'
  get '/settings' => 'movies#settings', as: 'settings'

  devise_for :users

  resources :theatres
  get '/movie/:movie_id/tickets' => "tickets#index", as: "ticket"
  get '/movie/:movie_timing_id/tickets/new' => "tickets#new", as: "new_ticket"
  post '/tickets' => 'tickets#create', as: 'tickets'
  get '/user/tickets' => 'tickets#show', as: 'user_tickets'

  scope '/theatre/:theatre_id' do
    resources :screens
  end

  scope '/screen/:screen_id' do
    resources :timings
  end

  scope '/movie/:movie_id' do
    resources :movie_timings
  end

  resources :people, except: :new
  scope "/movies/:movie_id" do
    resources :movie_casts, only: [:new, :create, :destroy]
  end
  scope "/movies/:movie_id" do
    resources :movie_crews, only: [:new, :create, :destroy]
  end

  scope 'search' do
    get '' => 'search#create', as: 'create_search'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :genre, presence: true, uniqueness: true
  has_many :movie_genres
  has_many :movies, through: :movie_genres
end

app/models/language.rb
class Language < ApplicationRecord
  validates :language, presence: true, uniqueness: true
  has_many :movie_languages
  has_many :movies, through: :movie_languages
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :movie_languages , dependent: :destroy
  has_many :languages, through: :movie_languages
  accepts_nested_attributes_for :languages

  has_many :movie_genres , dependent: :destroy
  has_many :genres, through: :movie_genres
  accepts_nested_attributes_for :genres

  has_many :movie_casts , dependent: :destroy
  has_many :persons, through: :movie_casts

  has_many :movie_crews , dependent: :destroy
  has_many :persons, through: :movie_crews

  has_many :movie_timings
  has_many :timings, through: :movie_timings

  has_one_attached :image
  validate :image_format

  private

  def image_format
    return unless image.attached?
    if ["image/png", "image/jpeg"].include?(image.blob.content_type)
      if image.blob.byte_size > 10.megabytes
        errors.add(:image, 'size needs to be less than 10 MB')
        image.delete
      end
    else
      image.delete
      errors.add(:image, 'needs to be jpeg or png image')
    end
  end
end

app/models/movie_cast.rb
class MovieCast < ApplicationRecord
  belongs_to :movie
  belongs_to :person
end

app/models/movie_crew.rb
class MovieCrew < ApplicationRecord
  belongs_to :movie
  belongs_to :person
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :genre
  belongs_to :movie
end

app/models/movie_language.rb
class MovieLanguage < ApplicationRecord
  belongs_to :movie
  belongs_to :language
end

app/models/movie_timing.rb
class MovieTiming < ApplicationRecord
  belongs_to :movie
  belongs_to :timing
  has_many :tickets
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :movie_casts
  has_many :movies, through: :movie_casts

  has_many :movie_crews
  has_many :movies, through: :movie_crews

  has_one_attached :avatar
  validate :avatar_format

  private

  def avatar_format
    return unless avatar.attached?
    if ["image/png", "image/jpeg"].include?(avatar.blob.content_type)
      if avatar.blob.byte_size > 5.megabytes
        errors.add(:avatar, 'size needs to be less than 5MB')
        avatar.delete
      end
    else
      avatar.delete
      errors.add(:avatar, 'needs to be jpeg or png image')
    end
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/screen.rb
class Screen < ApplicationRecord
  belongs_to :theatre
  has_many :timings
end

app/models/theatre.rb
class Theatre < ApplicationRecord
  has_many :screens

  has_one_attached :image
  validate :image_format

  private

  def image_format
    return unless image.attached?
    if ["image/png", "image/jpeg"].include?(image.blob.content_type)
      if image.blob.byte_size > 5.megabytes
        errors.add(:image, 'size needs to be less than 5MB')
        image.delete
      end
    else
      image.delete
      errors.add(:image, 'needs to be jpeg or png image')
    end
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :movie_timing
  belongs_to :user
end

app/models/timing.rb
class Timing < ApplicationRecord
  belongs_to :screen
  validates :timing, presence: true, uniqueness: true
  has_many :movie_timings
  has_many :movies, through: :movie_timings
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  validate :avatar_format
  has_many :tickets
  
  private

  def avatar_format
    return unless avatar.attached?
    if ["image/png", "image/jpeg"].include?(avatar.blob.content_type)
      if avatar.blob.byte_size > 5.megabytes
        errors.add(:avatar, 'size needs to be less than 5MB')
        avatar.delete
      end
    else
      avatar.delete
      errors.add(:avatar, 'needs to be jpeg or png image')
    end
  end
end

app/controllers/timings_controller.rb
class TimingsController < ApplicationController
  def index
    @screen = Screen.find(params[:screen_id])
  end

  def new
    @screen = Screen.find(params[:screen_id])
    @timing = Timing.new
  end

  def create
    @screen = Screen.find(params[:screen_id])
    @timing = Timing.new(timing_params)
    if @timing.save
      @error = nil
    else
      @error = "Timing already exists."
    end
  end

  def edit
    @screen = Screen.find(params[:screen_id])
    @timing = Timing.find(params[:id])
  end

  def update
    @timing = Timing.find(params[:id])
    if @timing.update(timing_params)
      @error = nil
    else
      @error = "Timing already exists."
    end
  end

  def destroy
    @timing = Timing.find(params[:id])
    if @timing.destroy
      @error = nil
    else
      @error = "Timing already exists."
    end
  end

  private

  def timing_params
    params.require(:timing).permit(:screen_id, :timing)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/helpers/screens_helper.rb
module ScreensHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/timings_helper.rb
module TimingsHelper
end

app/views/timings/_form.html.erb
<% if @timing.timing.nil? %>
  <h5><strong>Add Timing</strong></h5>
<% else %>
  <h5><strong>Edit Timing - <%= get_screen_time(@timing.timing) %></strong></h5>
<% end %>

<%= form_for(@timing, remote: true) do |f| %>
  <%= f.hidden_field :screen_id, value: @screen.id %>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.time_field :timing, class: "form-control" %>
    </div>
    <div class="form-group col-md-6">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/timings/_timing.html.erb
<div id="timing-<%= timing.id %>">
  <div class="card">
    <div class="card-body text-center">
      <strong><%= get_screen_time(timing.timing) %></strong><br>
      <% if user_signed_in? %>
        <%= link_to edit_timing_path(screen_id: timing.screen.id, id: timing.id), remote: true, class: "btn btn-outline-link" do %>
          <i class="fa fa-pencil" aria-hidden="true"></i>
        <% end %>
        <%= link_to timing_path(screen_id: timing.screen.id, id: timing.id), method: :delete,
            data: {confirm: "Are you sure you want to delete?"}, remote: true, class: "btn btn-outline-link" do %>
          <i class="fa fa-trash" aria-hidden="true" style="color:red;"></i>
        <% end %>
      <% end %>
    </div>
  </div>

  <style media="screen">

     @media (min-width: 576px) {
         .card-columns {
             column-count: 1;
         }
     }

     @media (min-width: 768px) {
         .card-columns {
             column-count: 2;
         }
     }

     @media (min-width: 992px) {
         .card-columns {
             column-count: 4;
         }
     }

     @media (min-width: 1200px) {
         .card-columns {
             column-count: 5;
         }
     }

  </style>

</div>

app/views/timings/create.js.erb
$("#timing-form").html("");
<% if @error.nil? %>
  $("#timings").append("<%= j render @timing %>")
<% else %>
  $("#errors").append("<%= j render 'layouts/messages', alert: @error %>")
<% end %>

app/views/timings/destroy.js.erb
<% if @error.nil? %>
  $("#timing-<%= @timing.id %>").fadeOut()
<% else %>
  $("#errors").append("<%= j render 'layouts/messages', alert: @error %>")
<% end %>

app/views/timings/edit.js.erb
$("#timing-form").html("<%= j render 'form' %>");

app/views/timings/index.html.erb
<div id="errors"></div>
<div class="card">
  <div class="card-header text-center">
    <h5><strong>
      <%= @screen.theatre.name %>
    </strong></h5>
    <h5><%= @screen.name %></h5>
  </div>
  <div class="card-body">
    <div class="card-columns" id="timings">
      <%= render @screen.timings %>
    </div>
    <div id="timing-form"></div>
  </div>
  <div class="card-footer">
    <%= link_to "Add Timing", new_timing_path(screen_id: @screen.id), remote: true, class: "btn btn-secondary" %>
  </div>
</div>

app/views/timings/new.js.erb
$("#timing-form").html("<%= j render 'form' %>");

app/views/timings/update.js.erb
$("#timing-form").html("");
<% if @error.nil? %>
  $("#timing-<%= @timing.id %>").html("<%= j render @timing %>")
<% else %>
  $("#errors").append("<%= j render 'layouts/messages', alert: @error %>")
<% end %>