config/routes.rb
Rails.application.routes.draw do

  resources :genres, except: :new
  resources :languages, except: :new

  resources :movies
  root 'movies#index'
  get '/settings' => 'movies#settings', as: 'settings'

  devise_for :users

  resources :theatres
  get '/movie/:movie_id/tickets' => "tickets#index", as: "ticket"
  get '/movie/:movie_timing_id/tickets/new' => "tickets#new", as: "new_ticket"
  post '/tickets' => 'tickets#create', as: 'tickets'
  get '/user/tickets' => 'tickets#show', as: 'user_tickets'

  scope '/theatre/:theatre_id' do
    resources :screens
  end

  scope '/screen/:screen_id' do
    resources :timings
  end

  scope '/movie/:movie_id' do
    resources :movie_timings
  end

  resources :people, except: :new
  scope "/movies/:movie_id" do
    resources :movie_casts, only: [:new, :create, :destroy]
  end
  scope "/movies/:movie_id" do
    resources :movie_crews, only: [:new, :create, :destroy]
  end

  scope 'search' do
    get '' => 'search#create', as: 'create_search'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  def settings
  end

  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
    @language = Language.new
    @genre = Genre.new
  end

  def edit
    @language = Language.new
    @genre = Genre.new

    @languages = ""
    @movie.languages.map { |e| e.id }.each do |i|
      @languages << i.to_s
    end

    @genres = ""
    @movie.genres.map { |e| e.id }.each do |i|
      @genres << i.to_s
    end
  end

  def create
    @movie = Movie.new(movie_params)
    respond_to do |format|
      if @movie.save
        params[:movie][:language][:language].each do |i|
          MovieLanguage.create(movie_id: @movie.id, language_id: i.to_i)
        end
        params[:movie][:genre][:genre].each do |i|
          MovieGenre.create(movie_id: @movie.id, genre_id: i.to_i)
        end

        SendMovieMailJob.perform_later(@movie)

        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @movie.update(movie_params)
        update_langs(params[:movie][:language][:language])
        update_genres(params[:movie][:genre][:genre])

        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @languages = @movie.languages
    @genres = @movie.genres
  end

  def destroy
    @movie.image.delete if @movie.image.attached?
    @movie.destroy
    redirect_to root_path
  end

  private

  def update_langs(language)
    langs = @movie.languages.map { |e| e.id.to_s }

    to_add = language - langs
    to_delete = langs - language

    to_add.each do |i|
      MovieLanguage.create(movie_id: @movie.id, language_id: i.to_i)
    end

    to_delete.each do |i|
      MovieLanguage.find_by(movie_id: @movie.id, language_id: i.to_i).delete
    end
  end

  def update_genres(genre)
    movie = @movie.genres.map { |e| e.id.to_s }

    to_add = genre - movie
    to_delete = movie - genre

    to_add.each do |i|
      MovieGenre.create(movie_id: @movie.id, genre_id: i.to_i)
    end

    to_delete.each do |i|
      MovieGenre.find_by(movie_id: @movie.id, genre_id: i.to_i).delete
    end
  end

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:name, :synopsis, :premiere, :runtime, :image)
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<div id="lang-list" data-lang-list="<%= @languages %>"></div>
<div id="genre-list" data-genre-list="<%= @genres %>"></div>

<%= form_for(@movie) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :synopsis %>
    <%= f.text_area :synopsis, class: 'form-control', rows: 3, required: true %>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.label :premiere_on %>
      <%= f.date_field :premiere, class: 'form-control', min: Date.today, required: true %>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :running_time_in_minutes %>
      <%= f.number_field :runtime, class: 'form-control', min: 1, required: true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :preview_image %>
    <%= f.file_field :image, class: 'form-control-file' %>
  </div>

  <div class="form-group">
    <%= f.label "Language" %><br>
    <%= f.fields_for(@language) do |form| %>
        <%= form.select :language, Language.all.map { |e| [e.language, e.id] }, {},
            { multiple: true, id: "multiple-checkboxes", required: true} %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label "Genre" %><br>
    <%= f.fields_for(@genre) do |form| %>
      <%= form.select :genre, Genre.all.map { |e| [e.genre, e.id] }, {},
          { multiple: true, id: "genre-checkboxes", required: true} %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Back', :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

<script type="text/javascript">
  const element = document.getElementById('lang-list');
  const lang = String(element.getAttribute('data-lang-list'));
  const array = lang.split('');
  $('#multiple-checkboxes').val(array);

  const ele = document.getElementById('genre-list');
  const genre = String(ele.getAttribute('data-genre-list'));
  const arr = genre.split('');
  $('#genre-checkboxes').val(arr);
</script>

app/views/movies/_movie.html.erb
<a href="<%= movie_path(movie) %>" class="text-center">
  <div class="card">
    <div class="card-body text-center">
        <figure>
          <%= image_tag movie_image(movie) %>
        </figure>
        <h5 style="color:black;"><%= movie.name %></h5>
        <p style="color:black;">
          <small>
            <%= movie_genre(movie) %><br>
            <%= movie_language(movie) %>
          </small>
        </p>
    </div>
  </div>
</a>

app/views/movies/edit.html.erb
<div class="card">
  <div class="card-header text-center">
    <h5><strong><%= @movie.name %></strong></h5>
    <%= image_tag movie_image(@movie) if @movie.image.attached? %>
  </div>
  <div class="card-body">
    <%= render 'form' %>
  </div>
</div>

app/views/movies/index.html.erb
<h2 class="mt-4 mb-4"><strong>Movies</strong></h2>
<div class="card-columns">
  <%= render @movies %>
</div>

app/views/movies/new.html.erb
<div class="card">
  <div class="card-header text-center">
    <h5><strong>Add Movie</strong></h5>
  </div>
  <div class="card-body">
    <%= render 'form' %>
  </div>
</div>

app/views/movies/settings.html.erb
<div class="card-columns text-center mt-4">
  <a href="<%= genres_path %>">
    <div class="card">
      <div class="card-body">
        <h5><strong>Genres</strong></h5>
        <h5><%= Genre.all.count %></h5>
      </div>
    </div>
  </a>

  <a href="<%= languages_path %>">
    <div class="card">
      <div class="card-body">
        <h5><strong>Languages</strong></h5>
        <h5><%= Language.all.count %></h5>
      </div>
    </div>
  </a>

  <a href="<%= people_path %>">
    <div class="card">
      <div class="card-body">
        <h5><strong>Persons</strong></h5>
        <h5><%= Person.all.count %></h5>
      </div>
    </div>
  </a>

  <a href="<%= theatres_path %>">
    <div class="card">
      <div class="card-body">
        <h5><strong>Theatres</strong></h5>
        <h5><%= Theatre.all.count %></h5>
      </div>
    </div>
  </a>
</div>

<style media="screen">
  .card {
    background-color: #6c757d;
    color: #ffffff;
  }

    @media (min-width: 576px) {
        .card-columns {
            column-count: 1;
        }
    }

    @media (min-width: 768px) {
        .card-columns {
            column-count: 2;
        }
    }

    @media (min-width: 992px) {
        .card-columns {
            column-count: 3;
        }
    }

    @media (min-width: 1200px) {
        .card-columns {
            column-count: 4;
        }
    }
</style>

app/views/movies/show.html.erb
<div class="card mb-3">

  <% if @movie.image.attached? %>
  <div class="card-header text-center">
    <%= image_tag movie_image(@movie) %>
  </div>
  <% end %>

  <div class="card-body">
    <h3>
      <strong><%= @movie.name %></strong>
      <%= link_to movie_timings_path(movie_id: @movie.id), class: 'btn btn-primary' do %>
        Add Screen
      <% end %>
      <%= link_to "Buy Tickets", ticket_path(movie_id: @movie.id), class: "btn btn-secondary" %>
    </h3>

    <% @languages.each do |language| %>
      <%= link_to language.language, language_path(language), class: 'btn btn-outline-dark mb-2' %>
    <% end %><br>
    <% @genres.each do |genre| %>
      <%= link_to genre.genre, genre_path(genre), class: 'btn btn-secondary mb-2' %>
    <% end %>

    <p><small><strong>
      <i class="fa fa-calendar-o" aria-hidden="true"></i> <%= @movie.premiere %> &nbsp;
      <i class="fa fa-clock-o" aria-hidden="true"></i> <%= @movie.runtime/60 %> hrs <%= @movie.runtime%60 %> mins
    </strong></small></p>

    <p><%= simple_format(@movie.synopsis) %></p>

    <h5><strong>Casts</strong></h5>
    <div id="casts-container" class="card-columns">
      <%= render @movie.movie_casts %>
    </div>

    <h5><strong>Crews</strong></h5>
    <div id="crews-container" class="card-columns">
      <%= render @movie.movie_crews %>
    </div>

    <div id="casts" style="display:none">
      <h5><strong>Add Cast</strong></h5>
    </div>
    <div id="crews" style="display:none">
      <h5><strong>Add Crew</strong></h5>
    </div>

    <% if user_signed_in? %>
      <hr>
      <%= link_to edit_movie_path(@movie), class: 'btn btn-outline-link' do %>
        <i class="fa fa-pencil" aria-hidden="true" style="color:black"> Edit</i>
      <% end %>
      <%= link_to @movie, method: :delete, data: {confirm: "Are you sure you want to delete the movie?"}, class: 'btn btn-outline-link' do %>
        <i class="fa fa-trash" aria-hidden="true" style="color:red"> Delete</i>
      <% end %>
      <%= link_to new_movie_cast_path(movie_id: @movie.id), class: 'btn btn-outline-link', remote: true  do %>
        <i class="fa fa-plus" aria-hidden="true"> Cast</i>
      <% end %>
      <%= link_to new_movie_crew_path(movie_id: @movie.id), class: 'btn btn-outline-link', remote: true  do %>
        <i class="fa fa-plus" aria-hidden="true"> Crew</i>
      <% end %><br>
    <% end %>
  </div>
</div>

<style media="screen">
  @media (min-width: 576px) {
      .card-columns {
          column-count: 2;
      }
  }

  @media (min-width: 768px) {
      .card-columns {
          column-count: 3;
      }
  }

  @media (min-width: 992px) {
      .card-columns {
          column-count: 4;
      }
  }

  @media (min-width: 1200px) {
      .card-columns {
          column-count: 5;
      }
  }
</style>