config/routes.rb
Rails.application.routes.draw do

  resources :genres, except: :new
  resources :languages, except: :new

  resources :movies
  root 'movies#index'
  get '/settings' => 'movies#settings', as: 'settings'

  devise_for :users

  resources :theatres
  get '/movie/:movie_id/tickets' => "tickets#index", as: "ticket"
  get '/movie/:movie_timing_id/tickets/new' => "tickets#new", as: "new_ticket"
  post '/tickets' => 'tickets#create', as: 'tickets'
  get '/user/tickets' => 'tickets#show', as: 'user_tickets'

  scope '/theatre/:theatre_id' do
    resources :screens
  end

  scope '/screen/:screen_id' do
    resources :timings
  end

  scope '/movie/:movie_id' do
    resources :movie_timings
  end

  resources :people, except: :new
  scope "/movies/:movie_id" do
    resources :movie_casts, only: [:new, :create, :destroy]
  end
  scope "/movies/:movie_id" do
    resources :movie_crews, only: [:new, :create, :destroy]
  end

  scope 'search' do
    get '' => 'search#create', as: 'create_search'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :genre, presence: true, uniqueness: true
  has_many :movie_genres
  has_many :movies, through: :movie_genres
end

app/models/language.rb
class Language < ApplicationRecord
  validates :language, presence: true, uniqueness: true
  has_many :movie_languages
  has_many :movies, through: :movie_languages
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :movie_languages , dependent: :destroy
  has_many :languages, through: :movie_languages
  accepts_nested_attributes_for :languages

  has_many :movie_genres , dependent: :destroy
  has_many :genres, through: :movie_genres
  accepts_nested_attributes_for :genres

  has_many :movie_casts , dependent: :destroy
  has_many :persons, through: :movie_casts

  has_many :movie_crews , dependent: :destroy
  has_many :persons, through: :movie_crews

  has_many :movie_timings
  has_many :timings, through: :movie_timings

  has_one_attached :image
  validate :image_format

  private

  def image_format
    return unless image.attached?
    if ["image/png", "image/jpeg"].include?(image.blob.content_type)
      if image.blob.byte_size > 10.megabytes
        errors.add(:image, 'size needs to be less than 10 MB')
        image.delete
      end
    else
      image.delete
      errors.add(:image, 'needs to be jpeg or png image')
    end
  end
end

app/models/movie_cast.rb
class MovieCast < ApplicationRecord
  belongs_to :movie
  belongs_to :person
end

app/models/movie_crew.rb
class MovieCrew < ApplicationRecord
  belongs_to :movie
  belongs_to :person
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :genre
  belongs_to :movie
end

app/models/movie_language.rb
class MovieLanguage < ApplicationRecord
  belongs_to :movie
  belongs_to :language
end

app/models/movie_timing.rb
class MovieTiming < ApplicationRecord
  belongs_to :movie
  belongs_to :timing
  has_many :tickets
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :movie_casts
  has_many :movies, through: :movie_casts

  has_many :movie_crews
  has_many :movies, through: :movie_crews

  has_one_attached :avatar
  validate :avatar_format

  private

  def avatar_format
    return unless avatar.attached?
    if ["image/png", "image/jpeg"].include?(avatar.blob.content_type)
      if avatar.blob.byte_size > 5.megabytes
        errors.add(:avatar, 'size needs to be less than 5MB')
        avatar.delete
      end
    else
      avatar.delete
      errors.add(:avatar, 'needs to be jpeg or png image')
    end
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/screen.rb
class Screen < ApplicationRecord
  belongs_to :theatre
  has_many :timings
end

app/models/theatre.rb
class Theatre < ApplicationRecord
  has_many :screens

  has_one_attached :image
  validate :image_format

  private

  def image_format
    return unless image.attached?
    if ["image/png", "image/jpeg"].include?(image.blob.content_type)
      if image.blob.byte_size > 5.megabytes
        errors.add(:image, 'size needs to be less than 5MB')
        image.delete
      end
    else
      image.delete
      errors.add(:image, 'needs to be jpeg or png image')
    end
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :movie_timing
  belongs_to :user
end

app/models/timing.rb
class Timing < ApplicationRecord
  belongs_to :screen
  validates :timing, presence: true, uniqueness: true
  has_many :movie_timings
  has_many :movies, through: :movie_timings
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  validate :avatar_format
  has_many :tickets
  
  private

  def avatar_format
    return unless avatar.attached?
    if ["image/png", "image/jpeg"].include?(avatar.blob.content_type)
      if avatar.blob.byte_size > 5.megabytes
        errors.add(:avatar, 'size needs to be less than 5MB')
        avatar.delete
      end
    else
      avatar.delete
      errors.add(:avatar, 'needs to be jpeg or png image')
    end
  end
end

app/controllers/screens_controller.rb
class ScreensController < ApplicationController
  def new
    @theatre = Theatre.find(params[:theatre_id])
    @screen = @theatre.screens.build
    respond_to do |f|
      f.js
    end
  end

  def create
    @theatre = Theatre.find(params[:theatre_id])
    @screen = @theatre.screens.build(screen_params)
    begin
      @screen.save
    rescue ActiveRecord::RecordNotUnique
      @error = "#{@screen.name} already exists"
    end
    respond_to do |format|
      format.js
    end
  end

  def update
    @screen = Screen.find(params[:id])
    begin
      @screen.update(screen_params)
    rescue ActiveRecord::RecordNotUnique
      @error = "#{@screen.name} already exists"
    end
    respond_to do |format|
      format.js
    end
  end

  def show
    @theatre = Theatre.find(params[:theatre_id])
    @screen = Screen.find(params[:id])
  end

  def edit
    @screen = Screen.find(params[:id])
  end

  def destroy
    @screen = Screen.find(params[:id])
    begin
      @screen.destroy
    rescue
      @error = "#{@screen.name} can not be deleted as it is used already"
    end
    respond_to do |format|
      format.js
    end
  end

  private

  def screen_params
    params.require(:screen).permit(:name, :seats, :price_cents)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/helpers/screens_helper.rb
module ScreensHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/timings_helper.rb
module TimingsHelper
end

app/views/screens/_form.html.erb
<div class="card">
  <div class="card-header">
    <% if @screen.name.nil? %>
      <h5><strong>Add Screen</strong></h5>
    <% else %>
      <h5><strong>Edit Screen</strong></h5>
    <% end %>
  </div>
  <div class="card-body">
    <%= form_for(@screen, remote: true) do |f| %>

      <div class="form-row">
        <div class="form-group col-md-6">
          <%= f.label :name %>
          <%= f.text_field :name, required: true, class: 'form-control', placeholder: "Screen name" %>
        </div>
        <div class="form-group col-md-6">
          <%= f.label :no_of_seats %>
          <%= f.number_field :seats, required: true, autofocus: true, autocomplete: 'seats', class: 'form-control', min: 1 %>
        </div>
      </div>

      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
      </div>

    <% end %>
  </div>
</div>

app/views/screens/_screen.html.erb
<div id="screen-<%= screen.id %>">
  <div class="card mb-2">
    <div class="card-body text-center">
      <strong><%= screen.name %></strong><br>
      <small><%= screen.seats %> seats</small><br>
      <% if user_signed_in? %>
        <%= link_to edit_screen_path(id: screen.id, theatre_id: screen.theatre.id), remote: true, class: "btn btn-outline-link mt-1 mb-1" do %>
          <i class="fa fa-pencil" aria-hidden="true"></i>
        <% end %>
        <%= link_to screen_path(id: screen.id, theatre_id: screen.theatre.id), method: :delete, class: "btn btn-outline-link mt-1 mb-1", remote: true,
            data: {confirm: "Are you sure you want to delete - #{screen.name} ?"} do %>
            <i class="fa fa-trash" aria-hidden="true" style="color:red"></i>
        <% end %><br>
        <%= link_to timings_path(screen_id: screen.id), class: "btn btn-outline-primary mt-1 mb-1" do %>
          <i class="fa fa-plus" aria-hidden="true"> Add Timings</i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/screens/create.js.erb
$("#screen-form").html("");
<% if @error %>
  $("#errors").append("<%= j render 'layouts/messages', alert: @error %>");
<% else %>
  $("#screens").append("<%= j render @screen %>");
<% end %>

app/views/screens/destroy.js.erb
<% if @error %>
  $("#errors").append("<%= j render 'layouts/messages', alert: @error %>");
<% else %>
  $("#screen-<%= @screen.id %>").fadeOut();
<% end %>

app/views/screens/edit.js.erb
$("#screen-form").html("<%= j render 'form' %>");

app/views/screens/new.js.erb
$("#screen-form").html("<%= j render 'form' %>");

app/views/screens/show.html.erb
<div id="errors"></div>
<div class="card">
  <div class="card-body">
    <p class="text-center">
      <strong class="mb-2"><%= @theatre.name %></strong><br>
      <%= @screen.name %><br>
      <%= @screen.seats %> seats
    </p>
    <div id="screen-timings" class="card-columns text-center">
      <%= render @screen.screen_timings.order("timing") %>
    </div>
    <div id="timing-form"></div>
    <% if user_signed_in? %>
      <hr>
      <%= link_to new_screen_timing_path(screen_id: @screen.id), remote: true, class: "btn btn-outline-link" do %>
        <i class="fa fa-plus" aria-hidden="true"> &nbsp; Add Timings</i>
      <% end %>
    <% end %>
  </div>
</div>

<style media="screen">
  @media (min-width: 576px) {
      .card-columns {
          column-count: 2;
      }
  }

  @media (min-width: 768px) {
      .card-columns {
          column-count: 3;
      }
  }

  @media (min-width: 992px) {
      .card-columns {
          column-count: 4;
      }
  }

  @media (min-width: 1200px) {
      .card-columns {
          column-count: 5;
      }
  }

</style>

app/views/screens/update.js.erb
$("#screen-form").html("");
<% if @error %>
  $("#errors").append("<%= j render 'layouts/messages', alert: @error %>");
<% else %>
  $("#screen-<%= @screen.id %>").html("<%= j render @screen %>");
<% end %>