config/routes.rb
Rails.application.routes.draw do

  resources :genres, except: :new
  resources :languages, except: :new

  resources :movies
  root 'movies#index'
  get '/settings' => 'movies#settings', as: 'settings'

  devise_for :users

  resources :theatres
  get '/movie/:movie_id/tickets' => "tickets#index", as: "ticket"
  get '/movie/:movie_timing_id/tickets/new' => "tickets#new", as: "new_ticket"
  post '/tickets' => 'tickets#create', as: 'tickets'
  get '/user/tickets' => 'tickets#show', as: 'user_tickets'

  scope '/theatre/:theatre_id' do
    resources :screens
  end

  scope '/screen/:screen_id' do
    resources :timings
  end

  scope '/movie/:movie_id' do
    resources :movie_timings
  end

  resources :people, except: :new
  scope "/movies/:movie_id" do
    resources :movie_casts, only: [:new, :create, :destroy]
  end
  scope "/movies/:movie_id" do
    resources :movie_crews, only: [:new, :create, :destroy]
  end

  scope 'search' do
    get '' => 'search#create', as: 'create_search'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :genre, presence: true, uniqueness: true
  has_many :movie_genres
  has_many :movies, through: :movie_genres
end

app/models/language.rb
class Language < ApplicationRecord
  validates :language, presence: true, uniqueness: true
  has_many :movie_languages
  has_many :movies, through: :movie_languages
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :movie_languages , dependent: :destroy
  has_many :languages, through: :movie_languages
  accepts_nested_attributes_for :languages

  has_many :movie_genres , dependent: :destroy
  has_many :genres, through: :movie_genres
  accepts_nested_attributes_for :genres

  has_many :movie_casts , dependent: :destroy
  has_many :persons, through: :movie_casts

  has_many :movie_crews , dependent: :destroy
  has_many :persons, through: :movie_crews

  has_many :movie_timings
  has_many :timings, through: :movie_timings

  has_one_attached :image
  validate :image_format

  private

  def image_format
    return unless image.attached?
    if ["image/png", "image/jpeg"].include?(image.blob.content_type)
      if image.blob.byte_size > 10.megabytes
        errors.add(:image, 'size needs to be less than 10 MB')
        image.delete
      end
    else
      image.delete
      errors.add(:image, 'needs to be jpeg or png image')
    end
  end
end

app/models/movie_cast.rb
class MovieCast < ApplicationRecord
  belongs_to :movie
  belongs_to :person
end

app/models/movie_crew.rb
class MovieCrew < ApplicationRecord
  belongs_to :movie
  belongs_to :person
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :genre
  belongs_to :movie
end

app/models/movie_language.rb
class MovieLanguage < ApplicationRecord
  belongs_to :movie
  belongs_to :language
end

app/models/movie_timing.rb
class MovieTiming < ApplicationRecord
  belongs_to :movie
  belongs_to :timing
  has_many :tickets
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :movie_casts
  has_many :movies, through: :movie_casts

  has_many :movie_crews
  has_many :movies, through: :movie_crews

  has_one_attached :avatar
  validate :avatar_format

  private

  def avatar_format
    return unless avatar.attached?
    if ["image/png", "image/jpeg"].include?(avatar.blob.content_type)
      if avatar.blob.byte_size > 5.megabytes
        errors.add(:avatar, 'size needs to be less than 5MB')
        avatar.delete
      end
    else
      avatar.delete
      errors.add(:avatar, 'needs to be jpeg or png image')
    end
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/screen.rb
class Screen < ApplicationRecord
  belongs_to :theatre
  has_many :timings
end

app/models/theatre.rb
class Theatre < ApplicationRecord
  has_many :screens

  has_one_attached :image
  validate :image_format

  private

  def image_format
    return unless image.attached?
    if ["image/png", "image/jpeg"].include?(image.blob.content_type)
      if image.blob.byte_size > 5.megabytes
        errors.add(:image, 'size needs to be less than 5MB')
        image.delete
      end
    else
      image.delete
      errors.add(:image, 'needs to be jpeg or png image')
    end
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :movie_timing
  belongs_to :user
end

app/models/timing.rb
class Timing < ApplicationRecord
  belongs_to :screen
  validates :timing, presence: true, uniqueness: true
  has_many :movie_timings
  has_many :movies, through: :movie_timings
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  validate :avatar_format
  has_many :tickets
  
  private

  def avatar_format
    return unless avatar.attached?
    if ["image/png", "image/jpeg"].include?(avatar.blob.content_type)
      if avatar.blob.byte_size > 5.megabytes
        errors.add(:avatar, 'size needs to be less than 5MB')
        avatar.delete
      end
    else
      avatar.delete
      errors.add(:avatar, 'needs to be jpeg or png image')
    end
  end
end

app/controllers/movie_timings_controller.rb
class MovieTimingsController < ApplicationController
  def index
    @movie = Movie.find(params[:movie_id])
    @movie_timings = @movie.movie_timings
  end

  def new
    @movie_timing = MovieTiming.new
    @movie = Movie.find(params[:movie_id])
    @timings = timings_list
  end

  def edit
    @movie = Movie.find(params[:movie_id])
    @movie_timing = MovieTiming.find(params[:id])
    @timings = timings_list
  end

  def update
    @movie_timing = MovieTiming.find(params[:id])
    @movie = @movie_timing.movie
    begin
      @movie_timing.update(movie_timing_params)
    rescue ActiveRecord::RecordNotUnique
      @error = "Screen timing is already present."
    end
    respond_to do |f|
      f.js
    end
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @movie_timing = MovieTiming.new(movie_timing_params)
    begin
      @movie_timing.save
    rescue ActiveRecord::RecordNotUnique
      @error = "Screen timing is already present."
    end
    respond_to do |f|
      f.js
    end
  end

  def destroy
    @movie_timing = MovieTiming.find(params[:id])
    @movie_timing.destroy
  end

  private

  def movie_timing_params
    params.require(:movie_timing).permit(:movie_id, :timing_id, :screening_till, :price_cents)
  end

  def timings_list
    results = []
    Timing.all.each do |timing|
      screen = Screen.find(timing.screen_id)
      theatre = Theatre.find(screen.theatre_id)
      list = [(theatre.name + " - " + screen.name + " @ " + get_screen_time(timing.timing)), timing.id]
      results << list
    end
    return results
  end

  def get_screen_time(timing)
    s,t  = "", ""
    if timing[0..1].to_i < 12
      s = timing + " am"
    elsif timing[0..1].to_i == 12
      if timing[3..].to_i > 0
        s = timing + " pm"
      else
        s = timing + " am"
      end
    else
      s = ((timing[0..1].to_i)-12 ).to_s + timing[2..] + " pm"
    end
    return s
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movie_timings_helper.rb
module MovieTimingsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/helpers/screens_helper.rb
module ScreensHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/movie_timings/_form.html.erb
<div class="card">
  <div class="card-header text-center">
    <% if @movie_timing.timing.nil? %>
      <h5><strong>Add Screen</strong></h5>
    <% else %>
      <h5><strong>Edit Screen</strong></h5>
    <% end %>
  </div>
  <div class="card-body">
    <%= form_for(@movie_timing, remote: true) do |f| %>
      <%= f.hidden_field :movie_id, value: @movie.id %>
      <div class="form-group">
        <%= f.label "Select a screen" %>
        <%= f.select :timing_id, @timings, {}, {class: "form-control", required: true} %>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <%= f.label :screening_till %>
          <%= f.date_field :screening_till, min: (Date.today + 1), class: "form-control", required: true %>
        </div>
        <div class="form-group col-md-6">
          <%= f.label :price_cents %>
          <%= f.number_field :price_cents, class: "form-control", required: true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit "Submit", class: "btn btn-secondary mb-2" %>
      </div>
    <% end %>
  </div>
</div>

app/views/movie_timings/_movie_timing.html.erb
<div id="movie-timing-<%= movie_timing.id %>">
  <% timing = Timing.find(movie_timing.timing_id) %>
  <div class="card text-center">
    <div class="card-header">
      <%= image_tag theatre_image(timing.screen.theatre), class: "rounded-circle mb-1" %><br>
      <strong><%= timing.screen.theatre.name %><br>
              <%= timing.screen.name %></strong><br>
      <small><%= get_screen_time(timing.timing) %><br>
      Till <%= movie_timing.screening_till %><br>
      <i class="fa fa-inr" aria-hidden="true"></i> <%= movie_timing.price_cents %></small>
    </div>
    <div class="card-body">
      <%= link_to edit_movie_timing_path(movie_id: @movie.id, id: movie_timing.id), remote: true,
          class: "btn btn-outline-link" do %>
            <i class="fa fa-pencil" aria-hidden="true"></i>
      <% end %>
      <%= link_to movie_timing_path(movie_id: @movie.id, id: movie_timing.id), method: :delete, remote: true,
          data: {confirm: "Are you sure you want to delete?"}, class: "btn btn-outline-link" do %>
            <i class="fa fa-trash" aria-hidden="true" style="color:red"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/movie_timings/create.js.erb
$("#screen-form").html("");
<% if @error %>
  $("#errors").append("<%= j render 'layouts/messages', alert: @error %>");
<% else %>
  $("#movie-timings").append("<%= j render @movie_timing %>")
<% end %>

app/views/movie_timings/destroy.js.erb
$("#movie-timing-<%= @movie_timing.id %>").fadeOut();

app/views/movie_timings/edit.js.erb
$("#screen-form").html("<%= j render 'form' %>")

app/views/movie_timings/index.html.erb
<div id="errors"></div>
<div class="card">
  <div class="card-header text-center">
    <figure class="">
      <%= image_tag movie_image(@movie) %>
    </figure>
    <h5><strong><%= @movie.name %></strong></h5>
  </div>
  <div class="card-body">
    <div class="card-columns" id="movie-timings">
      <%= render @movie_timings %>  
    </div>
    <div id="screen-form"></div>
  </div>
  <div class="card-footer">
    <%= link_to "Add Screen", new_movie_timing_path(movie_id: @movie.id), remote: true, class: "btn btn-primary" %>
  </div>
</div>

app/views/movie_timings/new.js.erb
$("#screen-form").html("<%= j render 'form' %>")

app/views/movie_timings/update.js.erb
$("#screen-form").html("");
<% if @error %>
  $("#errors").append("<%= j render 'layouts/messages', alert: @error %>");
<% else %>
  $("#movie-timing-<%= @movie_timing.id %>").html("<%= j render @movie_timing %>")
<% end %>